### PR TITLE
unicode support emoji (unicode <= v10)

### PR DESCRIPTION
**Pull request by AubreyHewes**
### Problem
When running within the docker container it will support (currently) at most v6 (and not even complete v6 support)

Test https://emojipedia.org/unicode-6.0/ via the docker container and search _hundred_ and any _button_..

#### Dev/Testing Caveat
When running locally the application has access to the local OS fonts and so will probably support emoji-unicode till ^v10 (this is a dev / testing caveat). 

####  This fix is for the _docker_ container. 

This adds support for emoji unicode including v10 (via `Symbola`).  The latest `Symbola` font is included as the upstream is outdated.

Try via docker container http://DOCKER-IP:3000/pdf?accessKey=dev&url=%s
 * https://emojipedia.org/unicode-6.0/ (now works; was not complete)
 * https://emojipedia.org/unicode-7.0/ (now works; was unsupported)
 * https://emojipedia.org/unicode-8.0/ (now works; was unsupported)
 * https://emojipedia.org/unicode-9.0/ (now works; was unsupported)
 * https://emojipedia.org/unicode-10.0/ (now works; was unsupported)
 * https://emojipedia.org/unicode-11.0/ (does not work; is not official; upcoming june 2018)

### CODE REVIEW

**Comment by AubreyHewes** [comment]
I also have a branch for extra (non latin) unicode language support (asian, arabic, hebrew, etc).. though possibly this is outside of this project? 
Though this project does not deliver any possibilities for extensibility beyond copy/overwriting..

Let me know..

**Comment by msokk** [comment]
Hi, thanks. I'll try to merge this in the evening.
I've been wanting to do a 1.0 release for some time.

Btw, what was the docker warning? Dockerfile already had shell command line break characters.

**Comment by AubreyHewes** [comment]
Hi @msokk

docker build warns on the empty line without a line break char (though is not a real problem)

Maybe a better 1.0 release would be to use debian:stretch as a base image and also add asian, arabic, hebrew fonts for a better character coverage? Or is outside the scope of this project?

**Comment by msokk** [comment]
Sure, if rendering works okay with stretch. 
I'm happy to increase font coverage, I'm not currently pushing for image size. Question is what font packages?
https://packages.debian.org/source/stretch/fonts/ 
https://packages.debian.org/contrib/stretch/fonts/

**Comment by msokk** [comment]
Released this - https://github.com/msokk/electron-render-service/releases/tag/1.0.0

**Pull request merged**
